# Generated by Django 4.1.3 on 2022-11-17 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
    ]
