# Generated by Django 4.1.3 on 2022-11-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
