# Generated by Django 4.1.3 on 2022-12-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_category_image_remove_category_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
